# Generated by Django 5.2 on 2025-04-28 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pot_alter_watering_options_alter_watering_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='pots',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pot'),
        ),
    ]
