# Generated by Django 5.2 on 2025-04-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_flower_pots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='pots',
        ),
        migrations.AddField(
            model_name='flower',
            name='pots',
            field=models.ManyToManyField(to='main_app.pot'),
        ),
    ]
